export const AUTH_ROLES = {
  SUPER_ADMIN: 'SUPER_USER',
  STATE_ADMIN: 'STATE_ADMIN',
  SECTION_OFFICER: 'SECTION_OFFICER',
  SUB_DIVISIONAL_OFFICER: 'SUB_DIVISIONAL_OFFICER',
} as const

export type AuthRole = (typeof AUTH_ROLES)[keyof typeof AUTH_ROLES]

export const STAFF_ROLES: AuthRole[] = [
  AUTH_ROLES.SECTION_OFFICER,
  AUTH_ROLES.SUB_DIVISIONAL_OFFICER,
]
