export const ROUTES = {
  DASHBOARD: '/',
  // Super Admin routes
  SUPER_ADMIN: '/super-user',
  SUPER_ADMIN_OVERVIEW: '/super-user',
  SUPER_ADMIN_STATES_UTS: '/super-user/states-uts',
  SUPER_ADMIN_STATES_UTS_ADD: '/super-user/states-uts/add',
  SUPER_ADMIN_STATES_UTS_VIEW: '/super-user/states-uts/:tenantCode',
  SUPER_ADMIN_STATES_UTS_EDIT: '/super-user/states-uts/:tenantCode/edit',
  SUPER_ADMIN_MANAGE_ADMINS: '/super-user/manage-admins',
  SUPER_ADMIN_SUPER_USERS: '/super-user/super-users',
  SUPER_ADMIN_SUPER_USERS_ADD: '/super-user/super-users/add',
  SUPER_ADMIN_SUPER_USERS_VIEW: '/super-user/super-users/:id',
  SUPER_ADMIN_SUPER_USERS_EDIT: '/super-user/super-users/:id/edit',
  SUPER_ADMIN_CONFIGURATION: '/super-user/configuration',
  // State Admin routes
  STATE_ADMIN: '/state-admin',
  STATE_ADMIN_OVERVIEW: '/state-admin',
  STATE_ADMIN_CONFIGURATION: '/state-admin/configuration',
  STATE_ADMIN_HIERARCHY: '/state-admin/hierarchy',
  STATE_ADMIN_LANGUAGE: '/state-admin/language',
  STATE_ADMIN_WATER_NORMS: '/state-admin/water-norms',
  STATE_ADMIN_INTEGRATION: '/state-admin/integration',
  STATE_ADMIN_ESCALATIONS: '/state-admin/escalations',
  STATE_ADMIN_TEMPLATES: '/state-admin/templates',
  STATE_ADMIN_OPERATOR_SYNC: '/state-admin/operator-sync',
  STATE_ADMIN_STAFF_SYNC: '/state-admin/staff-sync',
  STATE_ADMIN_SCHEME_SYNC: '/state-admin/scheme-sync',
  STATE_ADMIN_SCHEME_MAPPINGS_SYNC: '/state-admin/scheme-mappings-sync',
  STATE_ADMIN_STATE_UT_ADMINS: '/state-admin/state-ut-admins',
  STATE_ADMIN_STATE_UT_ADMINS_ADD: '/state-admin/state-ut-admins/add',
  STATE_ADMIN_STATE_UT_ADMINS_VIEW: '/state-admin/state-ut-admins/:id',
  STATE_ADMIN_STATE_UT_ADMINS_EDIT: '/state-admin/state-ut-admins/:id/edit',
  // Shared authenticated routes
  PROFILE: '/profile',
  CHANGE_PASSWORD: '/change-password',
  // Auth routes
  LOGIN: '/login',
  LOGOUT: '/logout',
  CREATE_PASSWORD: '/createpassword',
  RESET_PASSWORD: '/resetpassword',
} as const
